config/routes.rb
Rails.application.routes.draw do
  
  resources :mining_types
  get 'welcome/index'
  
  resources :coins
  
  root to: 'welcome#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coin.rb
class Coin < ApplicationRecord
  belongs_to :mining_type#, optional: true
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
  has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  
  def set_locale
    if params[:locale]
      cookies[:locale] = params[:locale]
    end
    
    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: [:new, :edit, :update, :create]
  

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to @coin, notice: "Coin was successfully created." }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to @coin, notice: "Coin was successfully updated." }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy
    respond_to do |format|
      format.html { redirect_to coins_url, notice: "Coin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  
    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to @mining_type, notice: "Mining type was successfully created." }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to @mining_type, notice: "Mining type was successfully updated." }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
    @mining_type.destroy
    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "Mining type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @name = "Caruso"
    @date_ambience = Date.today
    # @locale_is = locale(I18n.locale) esse método não funciona
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_form.html.erb
<%= form_with(model: coin, local: true) do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
      <% coin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :acronym, class:"form-label" %>
    <%= form.text_field :acronym, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :url_image, class:"form-label" %>
    <%= form.text_field :url_image, class:"form-control" %>
    <%#= image_tag coin.url_image, size: "25x25" %>
  </div>
  
  <div class="field">
    <%= form.label :mining_type_id, class:"form-label" %>
    <%= form.select("mining_type_id", @mining_type_options, { include_blank: 'select'}, class:"form-control") %>
  </div>
  </br>
  <div class="actions">
    <%= form.submit nil, class:"btn btn-dark" %>
  </div>
<% end %>
</br>

app/views/coins/edit.html.erb
<h1><%= t('pages.edit.coin') %></h1>

<%= render 'form', coin: @coin %>

<%= link_to t('links.show'), @coin, type:"button", class:"btn btn-dark" %> |
<%= link_to t('links.back'), coins_path, type:"button", class:"btn btn-dark" %>

app/views/coins/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('activerecord.models.coin.others') %></h1>

<table class="table table-ligth table-hover">
  <thead>
    <tr>
      <th> <%= t('activerecord.attributes.coin.description') %></th>
      <th><%= t('activerecord.attributes.coin.acronym') %></th>
      <th><%= t('activerecord.attributes.coin.url_image') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coins.each do |coin| %>
      <tr>
        <td><%= coin.description %></td>
        <td><%= coin.acronym %></td>
        <td><%= image_tag coin.url_image, size: "25x25" %></td>
        <td><%= link_to t('links.show'), coin, type:"button", class:"btn btn-dark" %></td>
        <td><%= link_to t('links.edit'), edit_coin_path(coin), type:"button", class:"btn btn-dark" %></td>
        <td><%= link_to t('links.destroy'), coin, method: :delete, data: { confirm: t('identify.confirm') }, type:"button", class:"btn btn-dark" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new.coin'), new_coin_path, type:"button", class:"btn btn-dark" %>

app/views/coins/new.html.erb
<h1>New Coin</h1>

<%= render 'form', coin: @coin %>

<%= link_to 'Back', coins_path, type:"button", class:"btn btn-dark" %>

app/views/coins/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('activerecord.models.coin.one') %></h1>

</br>
</br>

<p>
  <strong><%= t('activerecord.attributes.coin.description') %></strong>
  <%= @coin.description %>
</p>

<p>
  <strong><%= t('activerecord.attributes.coin.acronym') %></strong>
  <%= @coin.acronym %>
</p>

<p>
  <strong><%= t('activerecord.attributes.coin.url_image') %></strong>
  <%= image_tag @coin.url_image, size: "25x25" %>
</p>

</br>
</br>

<%= link_to t('links.edit'), edit_coin_path(@coin), type:"button", class:"btn btn-dark" %> |
<%= link_to t('links.back'), coins_path, type:"button", class:"btn btn-dark" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogCurso</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# stylesheet_link_tag    'scaffolds', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="container-fluid bg-ligth">
  
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to t('home'), welcome_index_path, class:"nav-link active" %> 
      </li>
      <li class="nav-item">
        <%= link_to t("language.pt"), root_path(locale: 'pt-BR'), class:"nav-link active" %> 
      </li>
      <li class="nav-item">
        <%= link_to t("language.en"), root_path(locale: 'en'), class:"nav-link active" %> 
      </li>
    </ul>
      
    <%= yield %>
    <!--<script>$.notify("Okay","success");</script>-->

  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type, local: true) do |form| %>
  <% if mining_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mining_type.errors.count, "error") %> prohibited this mining_type from being saved:</h2>

      <ul>
      <% mining_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :acronym, class:"form-label" %>
    <%= form.text_field :acronym, class:"form-control" %>
  </div>
  </br>
  <div class="actions">
    <%= form.submit nil, class:"btn btn-dark"  %>
  </div>
<% end %>
</br>

app/views/mining_types/edit.html.erb
<h1><%= t('pages.edit.miningt') %></h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to t('links.show'), @mining_type, type:"button", class:"btn btn-dark" %> |
<%= link_to t('links.back'), mining_types_path, type:"button", class:"btn btn-dark" %>

app/views/mining_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('activerecord.models.mining_type.others') %></h1>

<table class="table table-ligth table-hover">
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.mining_type.description') %></th>
      <th><%= t('activerecord.attributes.mining_type.acronym') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mining_types.each do |mining_type| %>
      <tr>
        <td><%= mining_type.description %></td>
        <td><%= mining_type.acronym %></td>
        <td><%= link_to t('links.show'), mining_type, type:"button", class:"btn btn-dark" %></td>
        <td><%= link_to t('links.edit'), edit_mining_type_path(mining_type), type:"button", class:"btn btn-dark" %></td>
        <td><%= link_to t('links.destroy'), mining_type, method: :delete, data: { confirm: t('identify.confirm') }, type:"button", class:"btn btn-dark" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new.miningt'), new_mining_type_path, type:"button", class:"btn btn-dark" %>

app/views/mining_types/new.html.erb
<h1>New Mining Type</h1>

<%= render 'form', mining_type: @mining_type %>

<%= link_to 'Back', mining_types_path, type:"button", class:"btn btn-dark" %>

app/views/mining_types/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('activerecord.models.mining_type.one') %></h1>

</br>
</br>

<p>
  <strong><%= t('activerecord.attributes.mining_type.description') %>:</strong>
  <%= @mining_type.description %>
</p>

<p>
  <strong><%= t('activerecord.attributes.mining_type.acronym') %>:</strong>
  <%= @mining_type.acronym %>
</p>

</br>
</br>

<%= link_to t('links.edit'), edit_mining_type_path(@mining_type), type:"button", class:"btn btn-dark" %> |
<%= link_to t('links.back'), mining_types_path, type:"button", class:"btn btn-dark" %>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= t(:welcome) %></h1>
  <p class="lead"> <%#= @locale_is esse método não funciona %> <%= t(:country) %></p>
  <hr class="my-4">
  <!--<p class="lead"><%# I18n.t(:hello)%></p>-->
  
  <p class="lead"><%= t('dt') %>: <%= l(@date_ambience) %></p>
  
  <h3><%= link_to t('coin'), coins_path, type:"button", class:"btn btn-dark" %></h3>
  <h3><%= link_to t('m_type'), mining_types_path, type:"button", class:"btn btn-dark" %></h3>
  
  <!--<h3><%# t('identify.i_am') %> <%# @name %> <%# t('identify.you')%></h3>-->
</div>